import type { ImageSourcePropType } from 'react-native';

import type { StarterAvatarKey } from '@/domain/family';

export type MoodKey = 'neutral' | 'happy' | 'proud' | 'sleepy' | 'waiting' | 'sad' | 'crying';
export type MoodLifecycleKey = 'egg' | 'cracking' | 'baby' | 'growing' | 'developed';
export type CharacterMoodSources = Record<
  StarterAvatarKey,
  Record<MoodLifecycleKey, Record<MoodKey, ImageSourcePropType>>
>;

export const moodSources: CharacterMoodSources = {
  inci: {
    egg: {
      neutral: require('../../../../assets/characters/moods/inci/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/inci/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/inci/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/inci/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/inci/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/inci/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/inci/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/inci/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/inci/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/inci/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/inci/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/inci/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/inci/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/inci/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/inci/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/inci/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/inci/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/inci/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/inci/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/inci/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/inci/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/inci/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/inci/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/inci/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/inci/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/inci/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/inci/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/inci/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/inci/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/inci/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/inci/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/inci/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/inci/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/inci/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/inci/developed/crying.png'),
    },
  },
  piril: {
    egg: {
      neutral: require('../../../../assets/characters/moods/piril/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/piril/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/piril/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/piril/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/piril/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/piril/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/piril/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/piril/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/piril/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/piril/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/piril/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/piril/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/piril/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/piril/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/piril/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/piril/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/piril/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/piril/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/piril/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/piril/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/piril/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/piril/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/piril/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/piril/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/piril/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/piril/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/piril/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/piril/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/piril/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/piril/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/piril/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/piril/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/piril/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/piril/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/piril/developed/crying.png'),
    },
  },
  kaan: {
    egg: {
      neutral: require('../../../../assets/characters/moods/kaan/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/kaan/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/kaan/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/kaan/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/kaan/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/kaan/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/kaan/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/kaan/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/kaan/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/kaan/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/kaan/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/kaan/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/kaan/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/kaan/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/kaan/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/kaan/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/kaan/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/kaan/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/kaan/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/kaan/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/kaan/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/kaan/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/kaan/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/kaan/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/kaan/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/kaan/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/kaan/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/kaan/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/kaan/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/kaan/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/kaan/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/kaan/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/kaan/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/kaan/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/kaan/developed/crying.png'),
    },
  },
  milo: {
    egg: {
      neutral: require('../../../../assets/characters/moods/milo/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/milo/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/milo/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/milo/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/milo/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/milo/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/milo/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/milo/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/milo/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/milo/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/milo/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/milo/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/milo/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/milo/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/milo/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/milo/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/milo/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/milo/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/milo/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/milo/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/milo/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/milo/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/milo/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/milo/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/milo/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/milo/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/milo/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/milo/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/milo/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/milo/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/milo/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/milo/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/milo/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/milo/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/milo/developed/crying.png'),
    },
  },
  zipzip: {
    egg: {
      neutral: require('../../../../assets/characters/moods/zipzip/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/zipzip/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/zipzip/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/zipzip/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/zipzip/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/zipzip/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/zipzip/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/zipzip/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/zipzip/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/zipzip/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/zipzip/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/zipzip/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/zipzip/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/zipzip/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/zipzip/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/zipzip/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/zipzip/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/zipzip/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/zipzip/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/zipzip/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/zipzip/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/zipzip/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/zipzip/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/zipzip/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/zipzip/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/zipzip/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/zipzip/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/zipzip/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/zipzip/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/zipzip/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/zipzip/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/zipzip/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/zipzip/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/zipzip/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/zipzip/developed/crying.png'),
    },
  },
  topi: {
    egg: {
      neutral: require('../../../../assets/characters/moods/topi/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/topi/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/topi/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/topi/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/topi/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/topi/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/topi/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/topi/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/topi/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/topi/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/topi/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/topi/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/topi/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/topi/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/topi/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/topi/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/topi/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/topi/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/topi/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/topi/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/topi/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/topi/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/topi/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/topi/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/topi/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/topi/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/topi/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/topi/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/topi/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/topi/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/topi/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/topi/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/topi/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/topi/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/topi/developed/crying.png'),
    },
  },
  akil: {
    egg: {
      neutral: require('../../../../assets/characters/moods/akil/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/akil/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/akil/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/akil/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/akil/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/akil/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/akil/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/akil/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/akil/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/akil/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/akil/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/akil/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/akil/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/akil/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/akil/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/akil/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/akil/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/akil/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/akil/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/akil/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/akil/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/akil/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/akil/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/akil/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/akil/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/akil/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/akil/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/akil/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/akil/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/akil/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/akil/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/akil/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/akil/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/akil/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/akil/developed/crying.png'),
    },
  },
  uyku: {
    egg: {
      neutral: require('../../../../assets/characters/moods/uyku/egg/neutral.png'),
      happy: require('../../../../assets/characters/moods/uyku/egg/happy.png'),
      proud: require('../../../../assets/characters/moods/uyku/egg/proud.png'),
      sleepy: require('../../../../assets/characters/moods/uyku/egg/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/uyku/egg/waiting.png'),
      sad: require('../../../../assets/characters/moods/uyku/egg/sad.png'),
      crying: require('../../../../assets/characters/moods/uyku/egg/crying.png'),
    },
    cracking: {
      neutral: require('../../../../assets/characters/moods/uyku/cracking/neutral.png'),
      happy: require('../../../../assets/characters/moods/uyku/cracking/happy.png'),
      proud: require('../../../../assets/characters/moods/uyku/cracking/proud.png'),
      sleepy: require('../../../../assets/characters/moods/uyku/cracking/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/uyku/cracking/waiting.png'),
      sad: require('../../../../assets/characters/moods/uyku/cracking/sad.png'),
      crying: require('../../../../assets/characters/moods/uyku/cracking/crying.png'),
    },
    baby: {
      neutral: require('../../../../assets/characters/moods/uyku/baby/neutral.png'),
      happy: require('../../../../assets/characters/moods/uyku/baby/happy.png'),
      proud: require('../../../../assets/characters/moods/uyku/baby/proud.png'),
      sleepy: require('../../../../assets/characters/moods/uyku/baby/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/uyku/baby/waiting.png'),
      sad: require('../../../../assets/characters/moods/uyku/baby/sad.png'),
      crying: require('../../../../assets/characters/moods/uyku/baby/crying.png'),
    },
    growing: {
      neutral: require('../../../../assets/characters/moods/uyku/growing/neutral.png'),
      happy: require('../../../../assets/characters/moods/uyku/growing/happy.png'),
      proud: require('../../../../assets/characters/moods/uyku/growing/proud.png'),
      sleepy: require('../../../../assets/characters/moods/uyku/growing/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/uyku/growing/waiting.png'),
      sad: require('../../../../assets/characters/moods/uyku/growing/sad.png'),
      crying: require('../../../../assets/characters/moods/uyku/growing/crying.png'),
    },
    developed: {
      neutral: require('../../../../assets/characters/moods/uyku/developed/neutral.png'),
      happy: require('../../../../assets/characters/moods/uyku/developed/happy.png'),
      proud: require('../../../../assets/characters/moods/uyku/developed/proud.png'),
      sleepy: require('../../../../assets/characters/moods/uyku/developed/sleepy.png'),
      waiting: require('../../../../assets/characters/moods/uyku/developed/waiting.png'),
      sad: require('../../../../assets/characters/moods/uyku/developed/sad.png'),
      crying: require('../../../../assets/characters/moods/uyku/developed/crying.png'),
    },
  },
};
